name: appgap
description: "Flutter app for managing human and mec resources"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.0

  # Utilitaires
  path: ^1.8.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  intl: ^0.20.2

  # Firebase (versions stables et compatibles Flutter 3.7.x)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4

  # Base de données locale
  drift: ^2.16.0
  floor: ^1.4.2

  # JSON ↔ Dart
  json_annotation: ^4.9.0

  # Tableaux horizontaux
  horizontal_data_table: ^4.3.1

  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Générateurs de code
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  drift_dev: ^2.16.0
  json_serializable: ^6.9.0
  analyzer: ^6.11.0

  # Lints / règles de style
  flutter_lints: ^5.0.0

  # Bibliothèque SQLite native (nécessaire à drift)
  sqlite3_flutter_libs: ^0.5.33


flutter:
  uses-material-design: true
  assets:
    - assets/users.json
