name: appgap
description: "Flutter app for managing human and mec resources"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.8.0
  path_provider: ^2.0.0
  drift: ^2.4.0
  # Pour JSON ↔ Dart
  json_annotation: ^4.9.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  firebase_auth: ^4.17.3
  horizontal_data_table: ^4.3.1
  font_awesome_flutter: ^10.4.0
  firebase_messaging: ^14.6.5
  cloud_firestore: ^4.17.4
  firebase_core: ^2.31.1
  floor: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.8
  json_serializable: ^6.0.1
  drift_dev: ^2.4.0
  sqlite3_flutter_libs: ^0.5.0



flutter:
  assets:
    - assets/users.json
  uses-material-design: true