// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyKuZ9X4H56a8LryZ4S0aTq0on5C-QMY8',
    appId: '1:815261433445:web:7ce7ea0666ab9db893d08c',
    messagingSenderId: '815261433445',
    projectId: 'appgap-c64d0',
    authDomain: 'appgap-c64d0.firebaseapp.com',
    storageBucket: 'appgap-c64d0.firebasestorage.app',
    measurementId: 'G-X9B652KDK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ax7HuttqiJqJHZU7aCtgzluByuZA4Hs',
    appId: '1:815261433445:android:45e1e72a3ec9b6e793d08c',
    messagingSenderId: '815261433445',
    projectId: 'appgap-c64d0',
    storageBucket: 'appgap-c64d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4EIrjTRdyJFVjlbJxL9murQ2GlV1DsI',
    appId: '1:815261433445:ios:1c928eca2c7342f793d08c',
    messagingSenderId: '815261433445',
    projectId: 'appgap-c64d0',
    storageBucket: 'appgap-c64d0.firebasestorage.app',
    iosBundleId: 'com.gap.appgap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT4EIrjTRdyJFVjlbJxL9murQ2GlV1DsI',
    appId: '1:815261433445:ios:37908266a705c7da93d08c',
    messagingSenderId: '815261433445',
    projectId: 'appgap-c64d0',
    storageBucket: 'appgap-c64d0.firebasestorage.app',
    iosBundleId: 'com.example.aptest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyKuZ9X4H56a8LryZ4S0aTq0on5C-QMY8',
    appId: '1:815261433445:web:42e5ea08f3d8f4b993d08c',
    messagingSenderId: '815261433445',
    projectId: 'appgap-c64d0',
    authDomain: 'appgap-c64d0.firebaseapp.com',
    storageBucket: 'appgap-c64d0.firebasestorage.app',
    measurementId: 'G-K4WFK6VHSD',
  );
}
